sudo: false
        
language: cpp

compiler:
  - clang
  - gcc

before_script:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

script:
  - ./configure
  - make

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libv8-dev
      - gcc-4.8
      - g++-4.8
      - clang
